src/main/java/uk/gov/hmcts/reform/sandl/snlapi/Application.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/config/WebSecurityConfig.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/SessionController.java, src/main/resources/application.yaml, src/test/resources/application.yaml
For now, without full configured ENV variables, so it defaults to '*'
=> SL-772 related bugfix. Added CORS related changes

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/SessionController.java
=> return session id on creation

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/UserTransactionController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/services/EventsCommunicationService.java
=> Add endpoints for user transaction

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/SessionController.java
=> Feature/sl 954/drag and drop

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/ReportController.java
=> fix checkstyle

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/exceptions/OptimisticLockException.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/security/JwtTokenProvider.java
=> SL-995 missed code smells

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/security/JwtTokenProvider.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/security/JwtTokenProviderTest.java
=> Feature/sl 996/api/token provider

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/config/BeanConfiguration.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/services/EventsCommunicationService.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/GetWelcomeTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/services/EventsCommunicationServiceTest.java
=> Feature/sl 996/api/events service

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/config/RestTemplateConfiguration.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/services/EventsCommunicationService.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/HearingPartControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/PersonControllerTest.java
=> Feature/sl 996/api/hearing part controller

build.gradle, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/config/RestTemplateConfiguration.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/SearchControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/SecurityControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/UserTransactionControllerTest.java
=> Feature/sl 996/api/tests

tools/globals.postman_globals.json, tools/hmcts-snl-api.postman_collection.json
=> Collection for logging in that sets access token for further requests

build.gradle, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/Application.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/HearingPartController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/services/EventsCommunicationService.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/HearingPartControllerTest.java
https://tools.hmcts.net/jira/browse/SL-1111
add delete hearing part endpoint to api
```
[ ] Yes
[x] No
```
=> SL-1111 delete hearing part endpoint

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/HearingPartController.java, tools/postman-collections/globals.postman_globals.json, tools/postman-collections/hmcts-snl-api.postman_collection.json
=> Feature/sl 1472/transactional listing

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/config/WebSecurityConfig.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/security/JwtAuthenticationFilter.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/security/services/S2SAuthenticationService.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/security/services/S2SAuthenticationServiceTest.java
=> [PREVIEW] SL-1471 Now Api passes through the username to other services in claims

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/config/WebSecurityConfig.java, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/ReferenceDataController.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/ReferenceDataControllerTest.java
Backend part of getting the reference data
=> [PREVIEW] Feature/sl 1237/fetch reference data to the ui

src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/SessionController.java
=> SL-1488: amend Session

infrastructure/main.tf, src/main/resources/application.yaml
=> [PREVIEW] - extend

src/main/resources/application.yaml
=> SL-1722 qutation marks added

infrastructure/main.tf, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/ProblemController.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/ProblemControllerTest.java
Copy of #85 due to problems with Jenkins ...
=> [PREVIEW] SL-1875/spike sever side pagination on problems page

infrastructure/main.tf, infrastructure/variables.tf
=> [PREVIEW] SL-1872 shared infra

infrastructure/main.tf, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/ProblemController.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/ProblemControllerTest.java
=> Propagate sprint 6 changes to demo

build.gradle, src/main/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/HearingController.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/HearingControllerTest.java
=> Feature/sl 1551/search and find listing request

tools/hmcts-snl-api.postman_collection.json, tools/postman-collections/hmcts-snl-api.postman_collection.json
=> SL-1922 removed availability

infrastructure/main.tf
=> [PREVIEW] SL-2107: SL-2107 set the capacity and size - workaround for RDO-2917

src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/HearingControllerTest.java
=> SL-1971: SL-1971: controller test

src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/HearingControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlapi/controllers/SessionControllerTest.java
=> SL-1971: Add testss

Jenkinsfile_CNP, Jenkinsfile_parameterized, src/kubernetes/config.aat.yaml, src/kubernetes/config.saat.yaml, src/kubernetes/deployment.template.yaml, src/main/resources/application.yaml
=> [AKS] SL-1919: enable AKS build

dependency-check-suppressions.xml
=> SL-2195 update suppressions
